
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module PA1P2(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire c1,c2,c3;

//=======================================================
//  Structural coding
//=======================================================

fulladder fa0(.b(SW[0]),.a(SW[4]),.c(SW[8]),.c_out(c1),.s(LEDR[0]));
fulladder fa1(.b(SW[1]),.a(SW[5]),.c(c1),.c_out(c2),.s(LEDR[1]));
fulladder fa2(.b(SW[2]),.a(SW[6]),.c(c2),.c_out(c3),.s(LEDR[2]));
fulladder fa3(.b(SW[3]),.a(SW[7]),.c(c3),.c_out(LEDR[4]),.s(LEDR[3]));

endmodule

module fulladder(input a,b,c, output s,c_out);

assign c_out = (b&a)||(b&c)||(a&c);
assign s = (~a&b&~c)||(a&~b&~c)||(~a&~b&c)||(a&b&c);

endmodule